### ISSUE TITLE
Dio 4.0.6 doesn't work

### ISSUE THREAD

**Issue by alpuysal** [supertokens/supertokens-flutter#16]
SuperTokensInterceptorWrapper doesn't work.

Error: Bad state future already completed.

**Comment by rishabhpoddar** [comment]
This issue should be fixed in version >= 0.1.1.

If not, please feel free to reopen this issue

**Comment by alpuysal** [comment]
hi,
i have already downgrade dio v4.0.4 and reinstall supertoken_flutter 0.1.1 but it didn't work.
i get same error "StateError (Bad state: Future already completed)"

**Comment by nkshah2** [comment]
Reopening this since its still an issue

**Comment by iresharma** [comment]
Looking into this now

**Comment by nkshah2** [comment]
Hi @alpuysal,

We've released a fix for this issue, available in version `0.1.2`  of the SDK. We have tested it with Dio `4.0.4` and `4.0.6` and both versions seem to work fine now. Please upgrade to the latest version and let us know if the issue still persists (its still in analysis on pub.dev so should be available in some time). 

Closing this issue for now, feel free to re-open if the issue still persists
