### ISSUE TITLE
`dio` version update

### ISSUE THREAD

**Issue by stutid** [supertokens/supertokens-flutter#44]
Hello,
Are there any plans to update `dio`? The `dio` version is 4.0.0 which is 2 years old, due to which we are unable to use latest versions for other dependencies in our codebase.
I would like to help contribute if that's possible.
Thank you.

**Comment by nkshah2** [comment]
Hi @stutid 

The new version of Dio is a breaking change and we have not had the time to evaluate how this affects us. We are happy to accept contributions though

**Comment by nkshah2** [comment]
Hey @stutid 

Just following up on this

**Comment by rishabhpoddar** [comment]
The dependency version has now been updated.
