### ISSUE TITLE
Session does not exist

### ISSUE THREAD

**Issue by ttarbox** [supertokens/supertokens-flutter#51]
I'm able to send and verify an SMS OTP in my Flutter app, but I'm not able to get any session info on subsequent calls. Also, I'm using the HTTP Client and it does not inject a the Authentication header on requests to my backend.

What am I missing?

**Comment by rishabhpoddar** [comment]
It's likely a mis config from your end. Make sure that the apiDomain configured is the apiDomain that you use when making the sign in API call.

Also, make sure that you have added our interceptor as shown in the docs.

**Comment by rishabhpoddar** [comment]
Can i see the supertokens.init config on the frontend?

**Comment by ttarbox** [comment]
```
SuperTokens.init(
        apiDomain: "https://<REMOVED>.ngrok-free.app",
        apiBasePath: "/auth",
        tokenTransferMethod: SuperTokensTokenTransferMethod.HEADER);
  }
```

**Comment by ttarbox** [comment]
On the backend, I simply have: `Session.init()`

Stepping through the code on the front-end I see that the access token is still be delivered via sAccessToken cookie. I also confirmed that the `st-auth-mode` header is set to `header` on the outgoing request, but I still only get the cookie access code.

<img width="1058" alt="Screenshot 2023-11-29 at 12 42 52 PM" src="https://github.com/supertokens/supertokens-flutter/assets/152338568/11b2dea8-62d8-4fb7-8f88-13b592bd0aa5">

**Comment by rishabhpoddar** [comment]
Huh. Which version of the backend SDK are you using?

**Comment by ttarbox** [comment]
I'm using "supertokens-node": "^12.1.4" with fastify, based off of this example: https://github.com/lirantal/fastify-supertokens-example

The request headers for the /auth/signinup/code request are: `{Content-type: application/json; charset=utf-8, st-auth-mode: header, cookie: }`

**Comment by rishabhpoddar** [comment]
Hmm. Im not sure why the header contains `st-auth-mode: header, cookie:`. It should only be `st-auth-mode: header`. Also, im not sure why there is a `:` at the end of `cookie`. Could you post an image of the request headers just like you posted an image of the response headers?
