### ISSUE TITLE
Refused to set unsafe header "cookie"

### ISSUE THREAD

**Issue by akalitenya** [supertokens/supertokens-flutter#52]
Setup is passwordless (OTP token).

Supertokens-postgres 7.0.16
Backend - NestJS.
Frontend - 2 apps:
1) Angular using supertokens-web-js
2) Flutter web using supertokens_flutter

Everything seems to be working as it should, but I have "Refused to set unsafe header "cookie"" error on each request from flutter web to backend.

flutter api service:
```
import 'package:supertokens_flutter/http.dart' as superhttp;

...

final response = await superhttp.post(
  uri,
  headers: {
    'Content-type': 'application/json',
    'rid': 'passwordless',
  },
  body: json.encode(body),
);
```

![Screenshot 2024-01-07 at 12 19 51](https://github.com/supertokens/supertokens-flutter/assets/11003561/acf299f3-7f05-4dde-ba1b-a55f145f6ecf)

**Comment by rishabhpoddar** [comment]
We don't support flutter web at the moment via our SDK. So you should manage tokens on your own on flutter web, and not use our interceptors from the flutter SDK.

Here is more info on managing tokens on your own: https://supertokens.com/docs/session/quick-setup/handling-session-tokens#if-not-using-our-frontend-sdk
